language: python

# Cache the pip files
cache:
  directories:
    - $HOME/.cache/pip

# Use container infrastructure
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# Python versions to test
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Install the application
install: "pip install -r requirements-dev.txt"

# Do the tests
script:
  # Formatting
  - flake8
